version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_DB: owasp
      POSTGRES_USER: spanlorin
      POSTGRES_PASSWORD: owasp
    ports:
      - "5432:5432"
    volumes:
      - ./owasp-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./owasp-be
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/owasp
      - SPRING_DATASOURCE_USERNAME=spanlorin
      - SPRING_DATASOURCE_PASSWORD=owasp
    depends_on:
      - db

  frontend:
    build: ./owasp-fe
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  security-tests:
    build: ./owasp-security-tests
    container_name: security-tests
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      backend:
        condition: service_started
    # command: sleep infinity  # Ține containerul deschis, dar inactiv
    command: ["sh", "-c", "sleep 10 && pytest tests/ --disable-warnings && tail -f /dev/null"]

  csrf-attack:
    build: ./csrf_attack
    container_name: csrf-attack
    ports:
      - "9000:9000"
    volumes:
      - ./csrf_attack:/usr/src/app
    working_dir: /usr/src/app
    command: ["python", "-m", "http.server", "9000"]
